//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkovJuniorLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkovJuniorLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;colors&gt;
        ///  &lt;color symbol=&quot;B&quot; value=&quot;000000&quot; comment=&quot;Black&quot;/&gt;
        ///  &lt;color symbol=&quot;I&quot; value=&quot;1D2B53&quot; comment=&quot;Indigo&quot;/&gt;
        ///  &lt;color symbol=&quot;P&quot; value=&quot;7E2553&quot; comment=&quot;Purple&quot;/&gt;
        ///  &lt;color symbol=&quot;E&quot; value=&quot;008751&quot; comment=&quot;Emerald&quot;/&gt;
        ///  &lt;color symbol=&quot;N&quot; value=&quot;AB5236&quot; comment=&quot;browN&quot;/&gt;
        ///  &lt;color symbol=&quot;D&quot; value=&quot;5F574F&quot; comment=&quot;Dead, Dark&quot;/&gt;
        ///  &lt;color symbol=&quot;A&quot; value=&quot;C2C3C7&quot; comment=&quot;Alive, grAy&quot;/&gt;
        ///  &lt;color symbol=&quot;W&quot; value=&quot;FFF1E8&quot; comment=&quot;White&quot;/&gt;
        ///  &lt;color symbol=&quot;R&quot; value=&quot;FF004D&quot; comment=&quot;Red&quot;/&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string palette {
            get {
                return ResourceManager.GetString("palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;settings
        ///  squareSize=&quot;7&quot; smallSquareSize=&quot;3&quot; maxwidth=&quot;10&quot; zshift=&quot;2&quot;
        ///  hindent=&quot;30&quot; hgap=&quot;2&quot; harrow=&quot;10&quot; hline=&quot;14&quot;
        ///  vskip=&quot;2&quot; smallvskip=&quot;2&quot; fontshift=&quot;2&quot; afterfont=&quot;4&quot;
        ///  dense=&quot;True&quot; d3=&quot;True&quot;
        ///  background=&quot;222222&quot; inactive=&quot;666666&quot; active=&quot;ffffff&quot;
        ////&gt;
        ///.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Tamzen8x16b {
            get {
                object obj = ResourceManager.GetObject("Tamzen8x16b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Tamzen8x16r {
            get {
                object obj = ResourceManager.GetObject("Tamzen8x16r", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
